module.exports = {
  siteTitle: 'Three Sisters',
  siteDescription: 'Handcrafted Art & Calligraphy',
  siteDescriptionLong: 'Handcrafted Art & Calligraphy',
  siteShortName: 'Three Sisters',
  siteAuthor: 'exshak',
  siteUrl: 'https://threesisterss.com',
  pathPrefix: '/',
  backgroundColor: '#f7f7f7',
  themeColor: '#efdbca',
  favicon: 'src/assets/icons/logo.png',
  siteLogo: '',
  googleAnalyticsID: 'UA-XXXXXXXX-X',
  siteNav: [
    { to: '/', text: 'Home' },
    { to: '/shop', text: 'Shop' },
    { to: '/about', text: 'About' },
    { to: '/contact', text: 'Contact' },
  ],
  siteContact: {
    address: '',
    email: '',
    phone: '',
  },
  socialLinks: [
    { site: 'facebook', link: 'https://github.com/exshak' },
    { site: 'instagram', link: 'https://github.com/exshak' },
    { site: 'twitter', link: 'https://github.com/exshak' },
  ],
}
